import {
  Activity,
  AlertTriangle,
  BarChart3,
  CalendarClock,
  Database,
  FileSearch,
  Gauge,
  GitCompare,
  HeartPulse,
  ListChecks,
  Medal,
  Settings,
  Swords,
} from "lucide-react";
import type {
  CreativeNotes,
  DatabaseInspection,
  Diagnostic,
  NavItem,
  PushFitSettings,
  SaveCandidate,
  SnapshotMetadata,
  TableInfo,
  WeeklyPriority,
  WorkerProfile,
} from "./types";

export const navItems: NavItem[] = [
  { key: "save-import", label: "Save Import", icon: Database },
  { key: "dashboard", label: "Dashboard", icon: Gauge },
  { key: "weekly-priorities", label: "Weekly Priorities", icon: ListChecks },
  { key: "roster-audit", label: "Roster Audit", icon: FileSearch },
  { key: "push-groups", label: "Push Groups", icon: BarChart3 },
  { key: "push-mismatch", label: "Push Mismatch", icon: AlertTriangle },
  { key: "ratings-analytics", label: "Ratings Analytics", icon: Activity },
  { key: "rivalries", label: "Rivalries", icon: Swords },
  { key: "titles", label: "Titles", icon: Medal },
  { key: "booking-warnings", label: "Booking Warnings", icon: HeartPulse },
  { key: "ppv-build-checker", label: "PPV Build Checker", icon: CalendarClock },
  { key: "snapshot-comparison", label: "Snapshot Comparison", icon: GitCompare },
  { key: "settings", label: "Settings", icon: Settings },
];

export const mappingFields = [
  "Worker Name",
  "Company",
  "Brand or Show",
  "Push",
  "Disposition",
  "Popularity",
  "Momentum",
  "Morale",
  "Fatigue",
  "Injury Status",
  "Contract Status",
  "Current Title",
  "Title Holder",
  "Event Name",
  "Event Date",
  "Show Type",
  "Match Order",
  "Match Participants",
  "Match Winner",
  "Match Loser",
  "Match Type",
  "Match Rating",
  "Show Rating",
  "Match Length",
  "Segment Order",
  "Segment Type",
  "Segment Participants",
  "Segment Rating",
  "Segment Length",
  "Storyline",
  "Title Involved",
  "Tag Team",
  "Stable or Faction",
];

export const defaultPushFitSettings: PushFitSettings = {
  popularityWeight: 35,
  momentumWeight: 25,
  credibilityWeight: 15,
  ratingsWeight: 15,
  availabilityWeight: 10,
  thresholds: {
    mainEvent: 85,
    upperMidcard: 70,
    midcard: 45,
    lowerMidcard: 25,
  },
};

export const emptyCreativeNotes: CreativeNotes = {
  bookingIntent: "",
  creativePlan: "",
  protectedBookingNote: "",
  plannedTitleDirection: "",
  plannedTurn: "",
  plannedFeud: "",
  longTermPlan: "",
  shortTermPlan: "",
  doNotBook: false,
  doNotBeat: false,
  keepStrong: false,
  coolDown: false,
  repackage: false,
  creativeOverrideActive: false,
  ignoreFromAudit: false,
};

export const demoSave: SaveCandidate = {
  fileName: "ROH-large-save.db",
  fullPath:
    "/home/deck/.local/share/Steam/steamapps/compatdata/1157700/pfx/drive_c/users/steamuser/AppData/Roaming/ProWrestlingSimulator/saves/ROH-large-save.db",
  lastModified: new Date().toISOString(),
  fileSize: 52_428_800,
  detectedBy: ["extension", "sqlite_header"],
  readable: true,
  warning: null,
};

export const demoSnapshot: SnapshotMetadata = {
  id: "demo-snapshot",
  importedDate: new Date().toISOString(),
  sourceFileName: demoSave.fileName,
  sourcePath: demoSave.fullPath,
  fileSize: demoSave.fileSize,
  sourceLastModified: demoSave.lastModified,
  snapshotPath:
    "/home/deck/.local/share/pws-save-auditor/snapshots/ROH-large-save-demo.db",
};

const table = (
  name: string,
  columns: string[],
  rowCount: number,
  sampleRows: Record<string, unknown>[],
): TableInfo => ({
  name,
  rowCount,
  columns: columns.map((column) => ({
    name: column,
    dataType: "TEXT",
    notNull: false,
    primaryKey: column.toLowerCase() === "id",
  })),
  sampleRows,
});

export const demoInspection: DatabaseInspection = {
  path: demoSnapshot.snapshotPath,
  warnings: [],
  likelyMappings: {
    workersTable: "workers",
    companiesTable: "companies",
    contractsTable: "contracts",
    brandsOrShowsTable: "shows",
    titlesTable: "titles",
    eventsTable: "events",
    matchesTable: "matches",
    segmentsTable: "angles",
    storylinesTable: "storylines",
    tagTeamsTable: "tag_teams",
    stablesOrFactionsTable: "stables",
  },
  tables: [
    table(
      "workers",
      [
        "id",
        "name",
        "company",
        "brand",
        "push",
        "disposition",
        "popularity",
        "momentum",
        "morale",
        "fatigue",
        "injury_status",
        "contract_status",
      ],
      84,
      [
        {
          id: 1,
          name: "Athena",
          company: "ROH",
          brand: "ROH",
          push: "Main Event",
          disposition: "Heel",
          popularity: 86,
          momentum: 88,
          morale: 74,
          fatigue: 36,
          injury_status: "Healthy",
          contract_status: "Written",
        },
        {
          id: 2,
          name: "Mark Briscoe",
          company: "ROH",
          brand: "ROH",
          push: "Main Event",
          disposition: "Face",
          popularity: 82,
          momentum: 71,
          morale: 68,
          fatigue: 61,
          injury_status: "Healthy",
          contract_status: "Written",
        },
        {
          id: 3,
          name: "Billie Starkz",
          company: "ROH",
          brand: "ROH",
          push: "Upper Midcard",
          disposition: "Face",
          popularity: 66,
          momentum: 84,
          morale: 80,
          fatigue: 27,
          injury_status: "Healthy",
          contract_status: "Written",
        },
      ],
    ),
    table("companies", ["id", "name"], 5, [
      { id: 1, name: "ROH" },
      { id: 2, name: "AEW" },
      { id: 3, name: "NJPW" },
    ]),
    table("titles", ["id", "name", "company", "champion", "last_defence"], 6, [
      {
        id: 1,
        name: "ROH World Championship",
        company: "ROH",
        champion: "Mark Briscoe",
        last_defence: "2026-04-02",
      },
    ]),
    table("matches", ["event", "date", "participants", "winner", "rating"], 342, []),
    table("angles", ["event", "date", "participants", "segment_type", "rating"], 188, []),
  ],
};

const demoOverall = (
  overallRating: number,
  marketability: number,
  starPower: number,
  popularity: number,
  wrestlingAbility: number,
  psychology: number,
  entertainment: number,
  reliability: number,
) => ({
  overallRating,
  overallBreakdown: {
    marketability,
    starPower,
    popularity,
    wrestlingAbility,
    psychology,
    entertainment,
    reliability,
  },
});

export const demoWorkers: WorkerProfile[] = [
  {
    id: "athena",
    name: "Athena",
    ...demoOverall(84, 88, 86, 86, 82, 84, 80, 78),
    company: "ROH",
    brandOrShow: "ROH",
    push: "Main Event",
    disposition: "Heel",
    popularity: 86,
    momentum: 88,
    morale: 74,
    fatigue: 36,
    injuryStatus: "Healthy",
    contractStatus: "Written",
    currentTitles: ["ROH Women's World Championship"],
    recentRecord: "5-1",
    recentMatchRatingAverage: 82,
    recentSegmentRatingAverage: 78,
    lastBooked: "9 days ago",
    warnings: ["Title defence due soon"],
    creativeNotes: { ...emptyCreativeNotes, keepStrong: true },
  },
  {
    id: "mark-briscoe",
    name: "Mark Briscoe",
    ...demoOverall(79, 82, 80, 82, 78, 76, 74, 81),
    company: "ROH",
    brandOrShow: "ROH",
    push: "Main Event",
    disposition: "Face",
    popularity: 82,
    momentum: 71,
    morale: 68,
    fatigue: 61,
    injuryStatus: "Healthy",
    contractStatus: "Written",
    currentTitles: ["ROH World Championship"],
    recentRecord: "3-2",
    recentMatchRatingAverage: 76,
    recentSegmentRatingAverage: 70,
    lastBooked: "16 days ago",
    warnings: ["Fatigue watch", "Champion not booked recently"],
    creativeNotes: { ...emptyCreativeNotes },
  },
  {
    id: "billie-starkz",
    name: "Billie Starkz",
    ...demoOverall(73, 72, 70, 66, 77, 74, 71, 76),
    company: "ROH",
    brandOrShow: "ROH",
    push: "Upper Midcard",
    disposition: "Face",
    popularity: 66,
    momentum: 84,
    morale: 80,
    fatigue: 27,
    injuryStatus: "Healthy",
    contractStatus: "Written",
    currentTitles: [],
    recentRecord: "5-1",
    recentMatchRatingAverage: 74,
    recentSegmentRatingAverage: 73,
    lastBooked: "4 days ago",
    warnings: ["Possible Upward Movement"],
    creativeNotes: { ...emptyCreativeNotes, plannedFeud: "Women's title programme" },
  },
  {
    id: "lee-moriarty",
    name: "Lee Moriarty",
    ...demoOverall(70, 64, 62, 57, 82, 75, 61, 78),
    company: "ROH",
    brandOrShow: "ROH",
    push: "Midcard",
    disposition: "Heel",
    popularity: 57,
    momentum: 76,
    morale: 64,
    fatigue: 22,
    injuryStatus: "Healthy",
    contractStatus: "Written",
    currentTitles: [],
    recentRecord: "4-1",
    recentMatchRatingAverage: 77,
    recentSegmentRatingAverage: 62,
    lastBooked: "7 days ago",
    warnings: ["Better in matches than segments"],
    creativeNotes: { ...emptyCreativeNotes },
  },
  {
    id: "undercard-worker",
    name: "Underused Prospect",
    ...demoOverall(52, 48, 45, 42, 61, 55, 50, 58),
    company: "ROH",
    brandOrShow: "ROH",
    push: "Lower Midcard",
    disposition: "Face",
    popularity: 42,
    momentum: 39,
    morale: 47,
    fatigue: 18,
    injuryStatus: "Healthy",
    contractStatus: "Handshake",
    currentTitles: [],
    recentRecord: "0-2",
    recentMatchRatingAverage: 60,
    recentSegmentRatingAverage: 55,
    lastBooked: "48 days ago",
    warnings: ["Not booked recently", "Low morale risk"],
    creativeNotes: { ...emptyCreativeNotes },
  },
];

export const diagnostics: Diagnostic[] = [
  {
    id: "champion-inactive",
    problem: "Champion has not defended recently.",
    severity: "High",
    evidence: "ROH World Champion has not defended in the current snapshot window.",
    whyItMatters: "Long title inactivity can make the championship feel less important.",
    suggestedFix: "Book a title defence or establish a clear number one contender.",
    exampleBookingAction:
      "Run a contender match on the next show and announce the title match for the next major event.",
  },
  {
    id: "upper-midcard-wins",
    problem: "Upper Midcard challenger pool needs credible wins.",
    severity: "Medium",
    evidence: "Only one Upper Midcard worker has a winning recent record in the ROH sample.",
    whyItMatters: "Title programmes need opponents who feel active and protected.",
    suggestedFix: "Give an Upper Midcard babyface a protected win before the next title challenge.",
    exampleBookingAction:
      "Book Billie Starkz over a comparable Push opponent, then follow up with a segment.",
  },
  {
    id: "repeated-match-risk",
    problem: "Repetitive matchup risk.",
    severity: "Low",
    evidence: "The match table is detected, but pairing analysis needs confirmed mapping.",
    whyItMatters: "Repeated singles matches can cool off otherwise useful rivalries.",
    suggestedFix: "Confirm Match Participants, Match Winner, Match Loser and Event Date mapping.",
    exampleBookingAction:
      "Rotate the next TV match into a tag or contender match until the major event.",
  },
];

export const weeklyPriorities: WeeklyPriority[] = [
  {
    priorityNumber: 1,
    issue: "Advance the ROH Women's Title programme.",
    suggestedAction: "Book one strong challenger segment and a protected contender win.",
    relatedItem: "ROH Women's World Championship",
    severity: "High",
    supportingEvidence: "Champion is strong, but challenger direction should be explicit.",
  },
  {
    priorityNumber: 2,
    issue: "Rest a high-fatigue Main Event worker.",
    suggestedAction: "Use a promo or tag involvement instead of another singles match.",
    relatedItem: "Main Event Push group",
    severity: "Medium",
    supportingEvidence: "A champion-level worker is nearing the fatigue warning threshold.",
  },
  {
    priorityNumber: 3,
    issue: "Build an Upper Midcard babyface win.",
    suggestedAction: "Create one clean win over an equal Push opponent.",
    relatedItem: "Upper Midcard Push group",
    severity: "Medium",
    supportingEvidence: "The next challenger pool needs credibility.",
  },
  {
    priorityNumber: 4,
    issue: "Avoid repeating the same singles match again this month.",
    suggestedAction: "Use a tag, angle or contender match to keep the rivalry fresh.",
    relatedItem: "Match variety",
    severity: "Low",
    supportingEvidence: "Pairing analysis will become exact after match mapping is confirmed.",
  },
  {
    priorityNumber: 5,
    issue: "Review underused lower-card workers.",
    suggestedAction: "Either book a short direction or mark Ignore from Audit.",
    relatedItem: "Lower Midcard and Opener depth",
    severity: "Low",
    supportingEvidence: "One sample worker has not been booked recently.",
  },
];
